ecs_cluster_name = "soon-ecs-cluster-prod"
ecs_service_name = "soon-ecs-service-prod"
ecs_task_defn_family = "soon-ecs-task-def-prod"
ecs_container_name = "soon-container-prod"
ecs_port_name = "soon-3000-tcp-prod"